---
title: Centralia Downtown Association - Meet me in Centralia!
timezone: UTC
collections:
  banner:
    title: Banner
    output: true
  cards:
    title: Cards
    output: true
  posts:
    title: Posts
    output: true
  splash:
    title: Splash
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: The Centralia Downtown Association is your family's best source for things
  to do in  Centralia WA! Find resources for visitors in Centralia and links to great
  resources in  Lewis County. Historic downtown Centralia has charming restaurants,
  antique shopping  and local arts. We are halfway between Portland and Seattle, and
  a great stop for your  next adventure!
baseurl: "/cda-website"
url: https://trallspnw.github.io
permalink: /:slug
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
