---
title: Centralia Downtown Association - Meet me in Centralia!
timezone: UTC
collections:
  banners:
    title: Banners
    output: true
  content-blocks:
    title: Content Blocks
    output: true
  homepage-cards:
    title: Homepage Cards
    output: true
  homepage-featured:
    title: Homepage Featured
    output: true
  homepage-hero:
    title: Homepage Hero
    output: true
  navigation_menu:
    title: Navigation Menu
    output: true
    permalink: "/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: banner
  values:
    layout: partial
- scope:
    path: ''
    type: hero
  values:
    layout: partial
    alignment: center
- scope:
    path: ''
    type: featured
  values:
    layout: partial
- scope:
    path: ''
    type: cards
  values:
    layout: partial
email: your-email@example.com
description: The Centralia Downtown Association is your family's best source for things
  to do in  Centralia WA! Find resources for visitors in Centralia and links to great
  resources in  Lewis County. Historic downtown Centralia has charming restaurants,
  antique shopping  and local arts. We are halfway between Portland and Seattle, and
  a great stop for your  next adventure!
baseurl: ''
url: https://cda.rallspnw.com
permalink: "/:slug"
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
