---
title: Centralia Downtown Association - Meet me in Centralia!
timezone: UTC
collections:
  banner:
    title: Banner
    output: true
  cards:
    title: Cards
    output: true
  hero:
    title: Hero
    output: true
  navigation_pages:
    title: Navigation Pages
    output: true
    permalink: "/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
email: your-email@example.com
description: The Centralia Downtown Association is your family's best source for things
  to do in  Centralia WA! Find resources for visitors in Centralia and links to great
  resources in  Lewis County. Historic downtown Centralia has charming restaurants,
  antique shopping  and local arts. We are halfway between Portland and Seattle, and
  a great stop for your  next adventure!
baseurl: ''
url: https://cda.rallspnw.com
permalink: "/:slug"
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
