# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: copy-to-prod

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["mainline"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build and Deploy
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with: 
          repository: trallspnw/cda-website
          path: cda-website
      - name: Checkout Target
        uses: actions/checkout@v3
        with:
          repository: trallspnw/cda-website-prod
          path: cda-website-prod
      - name: Config Global Git
        run: |
          git config --global user.email "tralls.pnw@gmail.com"
          git config --global user.name "trallspnw"
      - name: Gut Prod Content
        run: |
          mv cda-website-prod/.git prod-git-backup
          rm -rf cda-website-prod/*
          rm -rf cda-website-prod/.??*
          mv prod-git-backup cda-website-prod/.git
      - name: Copy Source to Temp
        run: |
          cd cda-website
          git fetch
          git checkout mainline
          cd ..
          cp -r cda-website temp
      - name: Clean Temp
        run: |
          cd temp
          rm -rf \
            .git \
            .github \
            .gitignore \
            CNAME \
            README.md
          mv .prod-files/* .
          rmdir .prod-files
          cd ..
      - name: Copy Temp to Prod
        run: |
          mv temp/* cda-website-prod/
      - name: Push to Prod
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          cd cda-website-prod
          git fetch
          git checkout prod
          git add .
          git commit -m "Promote mainline to prod"
          git remote -v
          git push -u https://trallspnw:$TOKEN@github.com/trallspnw/cda-website-prod prod
