# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: copy-to-prod

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["mainline"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build and Deploy
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with: 
          repository: trallspnw/cda-website
          path: cda-website
      - name: Checkout Target
        uses: actions/checkout@v3
        with:
          repository: trallspnw/cda-website-prod
          path: cda-website-prod
      - name: Copy and Push to Target
        run: |
          cd cda-website
          git fetch
          git checkout mainline
          rm -rf \
            .git \
            .github \
            .gitignore \
            CNAME \
            README.md
          mv .prod-files/* .
          rmdir .prod-files
          cp -r ../cda-website-prod/.git .
          git add .
          git commit -m "Sync prod from mainline"
          git push
      #    cp -r build/dist/* deploy
      #    cd deploy
      #    touch .nojekyll
      #    echo ${{ env.URL }} > CNAME
      #    git add .
      #    git commit -m $GITHUB_SHA
      #    git push
          
