name: 📕 Publish 🎉

on: 
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  merge:
    # Merges dev to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: prod
          github_token: ${{ github.token }}
      - name: Deploy
        uses: ./.github/workflows/dual-branch-deploy.yml
