name: Publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Step
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: mainline
          github_token: ${{ github.token }}
