name: Publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Step
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git fetch
          git log
          git checkout mainline
          git log
          git branch -u origin/dev
          git pull --rebase
          git branch -u origin/mainline
          git push
